### ISSUE TITLE
unnormalized power densities

### ISSUE THREAD

**Issue by Amingeo** [elcorto/pwtools#3]
Dear developers,
thanks for the very interesting code. I have some questions:
 As far as I understood,pwtools yields the normalized power densities, while sometimes we would need unnormalized one.  would you provide some details how the code can be modified to yield such unnormalized power density?

As the second request, I am wondering, are there some strightforward way/examples for pwtools users who are not experts in python (like myself) to get spectral power density (unnormalized) from CP2K generated velocity xyz file which has a structure like the one bellow? (first column is the atomic labels and the next columns are xyz components of velocities).
Thanks in advance and best regards,
Amin
####################
the sample CP2K velocity output
     192
 i =        0, time =        0.000, E =      -368.9974887553
  O         0.0000886641       -0.0000911669       -0.0001021906
  H        -0.0002956863       -0.0004934272       -0.0007190413
  H         0.0014825795       -0.0010745990        0.0005481207
  O         0.0003332422       -0.0001536368        0.0000391431
  H         0.0004673263       -0.0005194924        0.0010338811
  H         0.0000057824       -0.0005089213        0.0006525857
  O        -0.0002933685       -0.0002304744       -0.0001533996
  H        -0.0008513052        0.0007130663       -0.0006748945

**Comment by elcorto** [comment]
Hi Amin

Thanks for your interest in the project, I'm glad that you find this useful and I'm happy to help.


Regarding documentation, there is [this][doc] (also linked from the github page). There is a [section on theory background regarding the PDOS calculation from MD data][doc_pdos]. This also contains material on zero-padding and smoothing (see also [`pwtools.signal.smooth`][doc_smooth] for smoothing by convolution with a kernel). You can also check out the doc strings of the functions in the [`pydos` module][doc_pydos] for additional in-depth information.

Regarding parsing CP2K data, pwtools has a [set of parsers (mostly for DFT-code output, but also lammps)][doc_parse]. See also [test_cp2k] and [test_velocity]. This gives you the velocities as a 3d numpy array of shape `(nstep, natoms, 3)`:

```py
>>> tr=pwtools.io.read_cp2k_md('cp2k.out')
>>> tr.velocity
```

Note that the parser [assumes the presence of certain files next to "cp2k.out"][code_cp2k_parse] (the file name "cp2k.out" is just an example, can be any name you like). If your velocity file is named different, then it is easy to adapt those lines. Also note that if the velocity file (e.g. `PROJECT-vel-1.xyz` by default) is not found, the parser automatically calculates the velocities from atom positions and timestep by finite diffs.

Then you can calculate the PDOS [like documented here][doc_pdos_api]. Note that you should also provide the atom masses, which you can get from `tr.mass` for instance.

```py
>>> from pwtools.constants import fs,rcm_to_Hz
>>> # or tr=pwtools.io.read_cp2k_md('cp2k.out')
>>> tr = Trajectory(...)
>>> # freq in [Hz] if timestep in [s]
>>> freq,dos = pdos(tr.velocity, m=tr.mass, dt=tr.timestep*fs,
...                 method='direct', npad=1)
>>> # frequency in [1/cm]
>>> plot(freq/rcm_to_Hz, dos)
```

Regarding normalization, the `pdos` function has an arg `area` to which the frequency-pdos curve's integral is normalized to, so you can choose any normalization you want. We don't have an option to switch that of, so you'd need to modify the code here (lines calling `num.norm_int` in `pdos`).

Hope that helps.


[doc]: https://elcorto.github.io/pwtools/
[doc_pdos]: https://elcorto.github.io/pwtools/written/background/phonon_dos.html
[doc_smooth]: https://elcorto.github.io/pwtools/generated/api/pwtools.signal.smooth.html#pwtools.signal.smooth
[doc_pydos]: https://elcorto.github.io/pwtools/generated/api/__sphinx_autodoc_module__pwtools.pydos.html
[doc_parse]: https://elcorto.github.io/pwtools/written/background/parsing.html
[test_cp2k]: https://github.com/elcorto/pwtools/blob/master/pwtools/test/test_cp2k.py
[test_velocity]: https://github.com/elcorto/pwtools/blob/master/pwtools/test/test_velocity.py
[code_cp2k_parse]: https://github.com/elcorto/pwtools/blob/master/pwtools/parse.py#L1843
[doc_pdos_api]: https://elcorto.github.io/pwtools/generated/api/pwtools.pydos.pdos.html#pwtools.pydos.pdos

**Comment by elcorto** [comment]
And see also https://github.com/elcorto/pwtools/blob/master/examples/phonon_dos/pdos_methods.py for even more theory and example code.

**Comment by Amingeo** [comment]
Hi Steve,
many thanks, it was so helpful.
Best regards, Amin

**Comment by elcorto** [comment]
Happy to help. If you have no further questions, feel free to close this one.
