### ISSUE TITLE
how to cite it?

### ISSUE THREAD

**Issue by Clivia117** [elcorto/pwtools#7]

**Comment by elcorto** [comment]
You can follow the DOI link in the README to https://zenodo.org/records/5640089 and use for instance 

```
Steve Schmerler. (2021). elcorto/pwtools: (1.2.3). Zenodo. https://doi.org/10.5281/zenodo.5640089
```

if you used a specific release or just 

```
Steve Schmerler, https://github.com/elcorto/pwtools, https://doi.org/10.5281/zenodo.5640089
```

**Comment by Clivia117** [comment]
thank you!

**Comment by elcorto** [comment]
If you don't have any further questions, please don't forget to close this issue. Thanks.
